name: Generate Datas

on:
  schedule: # execute every 12 hours
    - cron: "* */12 * * *"
  workflow_dispatch:

jobs:
  build:
    name: Jobs to update datas
    runs-on: ubuntu-latest
    steps:
      # Snake Animation
      - uses: rhuanhianc/pac-snk@main
        id: pacman
        with:
          github_user_name: rhuanhianc
          outputs: |
            dist/github-pacman.svg?palette=pacman
            dist/github-pacman-dark.svg?palette=pacman-dark

      - uses: crazy-max/ghaction-github-pages@v2.1.3
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  
